
# This is a basic workflow to help you get started with Actions
# Fill <your repository>, <your repository>
# Set github pages to branch gh-pages and in "docs" not root
# Create github token in repo/settings/secrets/actions with name "GithubToken"

name: Deploy obsidianhtml output directly to gh-pages branch

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Upgrading to latest pip
        run: |
          pip install --upgrade pip
      - name: Installing latest obsidian and cleaning up
        run: |
          git clone https://github.com/obsidian-html/obsidian-html
          sed -i 's/>light</>Minimal</g' obsidian-html/obsidianhtml/src/html/themes/popup.html
          sed -i 's/obsidian-light/Light/g' obsidian-html/obsidianhtml/src/html/themes/popup.html
          sed -i 's/obsidian-dark/Dark/g' obsidian-html/obsidianhtml/src/html/themes/popup.html
          pip install obsidian-html/. --upgrade

      # - name: Cloning your repo containing obsidian vault and config.yaml - with 'master branch'
      #   run: |
      #     # config.yaml must have right relative path to obsidian_folder_path_str: and obsidian_entrypoint_path_str:
      #     git clone git@github.com:gpQ4utjefs/himgk.git
      #     cd himgk
      #     python -m obsidianhtml -i config.yaml

      - name: Clone GuillaumeFalourd/formulas-training PRIVATE repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
          owner: 'gpQ4utjefs'
          repository: 'himgk'
          access-token: ${{ secrets.GithubToken }}
      - name: Access cloned repository content
        run: |
          cd himgk
          python -m obsidianhtml -i config.yaml
          ls -la

      - name: Rename - rename html to docs
        run: |
          cd himgk/output
          mv html docs
      
      - name: removing unwanted links
        run: |
          sed -i 's/^.+config\.yaml.+\n.+$//g' himgk/output/docs/index.html
         
      - name: Push to gh-pages branch --force
        # You may pin to the exact commit or the version.
        # uses: ftnext/action-push-ghpages@621f3b2f1d34079b4da6051daedb3e200af0dd38
        uses: ftnext/action-push-ghpages@v1.0.0
        with:
          # Path to the directory where the static assets are located.
          build_dir: /home/runner/work/himgk/himgk/himgk/output
          # Create github token in repo/settings/secrets/actions with name GithubToken
          github_token: ${{ secrets.GithubToken }}